### ISSUE TITLE
[Documentation] Could there be an explanation of token types a bit ?

### ISSUE THREAD

**Issue by yw662** [arguablykomodo/deno_rusty_markdown#1]
They are mostly self-explanatory, but I cannot see it clearly what is a `softBreak`, `hardBreak`, or `Rule`, and when they will be inserted to the token array.

Could there be some explanation of that ?

**Comment by arguablykomodo** [comment]
All of the parsing is done by the [`pulldown_cmark` library](https://github.com/raphlinus/pulldown-cmark) and is based on the [CommonMark Spec](https://spec.commonmark.org/0.30). The spec has more detailed explanations as to what [soft breaks](https://spec.commonmark.org/0.30/#soft-line-breaks), [hard breaks](https://spec.commonmark.org/0.30/#hard-line-breaks) and [horizontal rules](https://spec.commonmark.org/0.30/#thematic-breaks) are.
